import Head from "next/head";
import React from "react";

export default function Header(): JSX.Element {
  return (
    <Head>
      <meta charSet="UTF-8" />
      <meta name="viewport" content="width=device-width, initial-scale=1.0" />
      <meta name="description" content="Generated by create next app" />
      <title>Argent Bank - Home Page</title>
      <link
        rel="stylesheet"
        href="https://stackpath.bootstrapcdn.com/font-awesome/4.7.0/css/font-awesome.min.css"
      />
      <link rel="icon" href="/favicon.ico" />
    </Head>
  );
}
